name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to AWS ECR
      - name: Log in to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t todoapp .
          docker tag todoapp:latest ${{ secrets.ECR_REPOSITORY }}:latest

      # Step 4: Push Docker image to ECR
      - name: Push to AWS ECR
        run: |
          docker push ${{ secrets.ECR_REPOSITORY }}:latest

      # Step 5: Install dependencies
      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Install Project Dependencies
        run: npm install

      # Step 6: Deploy to AWS Lambda
      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: serverless deploy
