name: Deploy to AWS Lambda

on: 
  workflow_dispatch: 
    inputs: 
      logLevel: 
        description: 'Log level' 
        required: true 
        default: 'warning' 
      environment: 
          description: 'Environment to deploy' 
          required: false 
          default: 'staging'

# on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Python dependencies
      run:         
        pip install -r requirements.txt

    - name: Install Serverless Framework
      run: npm install -g serverless@latest

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Log in to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2        

    - name: Build Docker image
      run: |
        docker build -t todoapp .
        docker tag my-app:latest ${{ secrets.ECR_REPOSITORY }}:latest

    - name: Push to AWS ECR
      run: |
          docker push ${{ secrets.ECR_REPOSITORY }}:latest        

    - name: Deploy to AWS Lambda
      env:
        SERVERLESS_ACCESS_TOKEN: ${{ secrets.SERVERLESS_ACCESS_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: serverless deploy
      # uses: serverless/github-action@v2
      # env:
      #   SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      # run: |
      #   echo "Deploying using Serverless..."
      #   serverless deploy

    - name: Post-deployment notification
      if: success()
      run: echo "Deployment successful!"