name: Deploy to AWS Lambda

on: 
  workflow_dispatch: 
    inputs: 
      logLevel: 
        description: 'Log level' 
        required: true 
        default: 'warning' 
      environment: 
        description: 'Environment to deploy' 
        required: false 
        default: 'staging'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Install Serverless Framework
      run: npm install -g serverless@latest

    - name: Clear NPM cache
      run: npm cache clean --force

    - name: Install Node.js dependencies with debug logging
      run: npm install --loglevel verbose

    - name: Reinstall Serverless Framework
      run: npm uninstall serverless && npm install serverless@latest
    
    - name: Reinstall Memoizee
      run: npm uninstall memoizee && npm install memoizee@latest

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Log in to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker image
      run: |
        echo "Building Docker image..."
        docker build -t todoapp .
        docker tag todoapp:latest ${{ secrets.ECR_REPOSITORY }}:latest

    - name: Push to AWS ECR
      run: |
        echo "Pushing Docker image to ECR..."
        docker push ${{ secrets.ECR_REPOSITORY }}:latest

    - name: Deploy to AWS Lambda
      uses: serverless/github-action@v2
      with:
        args: deploy
      env:
        SERVERLESS_ACCESS_TOKEN: ${{ secrets.SERVERLESS_ACCESS_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

    - name: Post-deployment notification
      if: success()
      run: echo "Deployment successful!"